Updated approach with local common module and common script_runner
aderiabin/sdl_atf_test_scripts pull request #2
Opened 2017-03-28 13:34 UTC by aderiabin

# Scenario based test script approach

## Step 1
- Create common module for CRQ or requirement group
- Create test_data module for CRQ or requirement group

## Step 2
- Exclude connect test implementation from script
- Implement example of scenario based test script 

## Step 3
- Add Title to report without creation separated test steps
- Implement example of scenario based script with functions with parameters

### Restriction:
Function which used as parameters in scenario steps and required <Test> as parameter should expect it as last parameter and mustn't set in scenario function
### Example:  
Function
```
function registerApplication(RAIParameters, test)
  local corIdRAI = test.mobileSession:SendRPC("RegisterAppInterface", RAIParameters)
  EXPECT_HMINOTIFICATION("BasicCommunication.OnAppRegistered",
    {
      application =
      {
        appName = RAIParameters.appName
      }
    })
  :Do(function(_,data)
      test.applications[RAIParameters.appName] = data.params.application.appID
    end)
  test.mobileSession:ExpectResponse(corIdRAI, { success = true, resultCode = "SUCCESS" })
end
```
should be called in scenario as:
`runner.Step("Register mobile application", registerApplication, {RAIParameters})`

2017-06-30 10:56 UTC, LuxoftAKutsan commented
Please add motivation of this approach and drawbacks

2017-06-30 10:57 UTC, LuxoftAKutsan requested changes
Not bad, but please add motivation and fix mentioned issues

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +local function checkFunction()
@aderiabin not clear from name what this function actually checks. Also `Function` is most always redundant part of  name of any function.

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +    commonFunctions:userPrint(31, RAIParameters.appID .. " icon is absent")
@aderiabin whe are you going to create some kind of enum for color constants?

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +    local oldFileToCheck = iconFolderPath.. "icon" .. i ..".png"
@aderiabin I remember some kind of path merge function

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +    local oldFileExistResult = commonSteps:file_exists(oldFileToCheck)
@aderiabin just as advice such variables are redundant.

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +  self.mobileSession:StartService(7)
@aderiabin looks like part of this function is something like an application registration. Please extract it ( or use some common function if exist) for clear understanding what does exact this function do.

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +              local pathToAppFolder = testData.pathToSdlStorage.. "/" .. RAIParameters.appID .. "_" .. config.deviceMAC .. "/"
@aderiabin please use function that merge paths

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +              local pathToAppFolder = testData.pathToSdlStorage.. "/" .. RAIParameters.appID .. "_" .. config.deviceMAC .. "/"
@aderiabin also try to avoid any activity between sending request and expecting response.

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
> +local function postconditions()
@aderiabin duplicating postcondition text is redundant. I would Name this function with naming of what it exact doing.

2017-06-30 10:57 UTC, LuxoftAKutsan commented on test_scripts/AppIconFolder/ATF_P_Remove_Old_AppIconsAmountToRemove_noSpace.lua
> +local function check_Deleted_one_old_icon_if_space_not_enough(self)
@aderiabin avoid mixing snake and camel case

2017-06-30 10:57 UTC, LuxoftAKutsan commented on user_modules/script_runner.lua
> +local runnerState = {
@aderiabin description required

2017-06-30 10:57 UTC, LuxoftAKutsan commented on user_modules/script_runner.lua
> +    stepNumber = stepNumber + 1
@aderiabin do you think that it is allowed situation? I would stop such test cases execution and force test engineer to give correct test step name

2017-06-30 10:57 UTC, LuxoftAKutsan commented on user_modules/script_runner.lua
> +    return function()
@aderiabin  would stop such test cases execution and force test engineer to give correct testStepImplFunction

2017-06-30 10:57 UTC, LuxoftAKutsan commented on user_modules/script_runner.lua
> +  local test = Test
@aderiabin please declare variables closer to usage

2017-07-04 10:28 UTC, aderiabin commented on user_modules/script_runner.lua
> +local runnerState = {
@LuxoftAKutsan `runnerState` table was removed.

2017-07-04 10:31 UTC, aderiabin commented on user_modules/script_runner.lua
> +    stepNumber = stepNumber + 1
@LuxoftAKutsan Default test step name generation was replaced with code that stop script execution with descriptive comment.

2017-07-04 10:31 UTC, aderiabin commented on user_modules/script_runner.lua
> +    return function()
@LuxoftAKutsan Default test step function generation was replaced with code that stop script execution with descriptive comment.

2017-07-04 10:32 UTC, aderiabin commented on user_modules/script_runner.lua
> +  local test = Test
@LuxoftAKutsan Fixed.

2017-09-18 12:20 UTC, closed without merging